### PR TITLE
Play playlist

### PR DESCRIPTION
**Pull request by huutuandn96**
## Related Tickets:
- [#38217](https://edu-redmine.sun-asterisk.vn/issues/38217)

## WHAT this PR does?
Play playlist and favorite list feature

### CODE REVIEW

**Comment by huutuandn96** [comment]
ready

**Comment by huutuandn96** [comment]
ready

**Comment by quoctd-0607** [comment]
commented
conflict code

**Comment by huutuandn96** [comment]
ready

**Pull request merged**
