### PR TITLE
Notification album

### PR DESCRIPTION
**Pull request by huutuandn96**
## Related Tickets:
- [#39474](https://edu-redmine.sun-asterisk.vn/issues/39474)

## WHAT this PR does?
Send the email when admin add new album

### CODE REVIEW

**Comment by huutuandn96** [comment]
ready

**Comment by huutuandn96** [comment]
ready

**Comment by quoctd-0607** [comment]
commented
conflict code

**Comment by huutuandn96** [comment]
ready

**Comment by quoctd-0607** [comment]
commented
conflict code

**Comment by huutuandn96** [comment]
ready

**Pull request merged**
